name: Build and Sign Blockchain Commit Images

on:
  push:
    branches-ignore:
      - 'release/[0-9]+.[0-9]+'
  workflow_dispatch:

concurrency: 
  group: build-commit-images-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # From Cloud Build trigger ff28b668-43bf-4c3a-8967-fbf6640fdf5f in celo-testnet
  # https://console.cloud.google.com/cloud-build/triggers;region=global/edit/ff28b668-43bf-4c3a-8967-fbf6640fdf5f?project=celo-testnet&supportedpurview=project
  Build-Container-geth-Anycommit:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.8
    if: github.ref != 'refs/heads/master'
    with:
      workload-id-provider: 'projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-blockchain-dev/providers/github-by-repos'
      service-account: 'celo-blockchain-dev@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/dev-images/geth
      tag: testing
      context: .

  # From Cloud Build trigger ff28b668-43bf-4c3a-8967-fbf6640fdf5f in celo-testnet
  # https://console.cloud.google.com/cloud-build/triggers;region=global/edit/ff28b668-43bf-4c3a-8967-fbf6640fdf5f?project=celo-testnet&supportedpurview=project
  Build-Container-geth-all-Anycommit:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.8
    if: github.ref != 'refs/heads/master'
    with:
      workload-id-provider: 'projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-blockchain-dev/providers/github-by-repos'
      service-account: 'celo-blockchain-dev@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/dev-images/geth-all
      tag: testing
      context: .
      file: Dockerfile.alltools

  # From Cloud Build trigger docker-branchname-tagged in celo-testnet
  # https://console.cloud.google.com/cloud-build/triggers;region=global/edit/dcf76f6d-b05b-4289-bb3b-de3e9b62efa5?project=celo-testnet&supportedpurview=project
  Build-Container-geth-master:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.8
    if: github.ref == 'refs/heads/master'
    with:
      workload-id-provider: 'projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-blockchain/providers/github-by-repos'
      service-account: 'celo-blockchain@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/celo-blockchain-public/geth
      tag: master
      context: .

  # From Cloud Build trigger docker-branchname-tagged in celo-testnet
  # https://console.cloud.google.com/cloud-build/triggers;region=global/edit/dcf76f6d-b05b-4289-bb3b-de3e9b62efa5?project=celo-testnet&supportedpurview=project
  Build-Container-geth-all-master:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.8
    if: github.ref == 'refs/heads/master'
    with:
      workload-id-provider: 'projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-blockchain/providers/github-by-repos'
      service-account: 'celo-blockchain@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/celo-blockchain-public/geth-all
      tag: master
      context: .
      file: Dockerfile.alltools
